spring:
  datasource:
    batch:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.61.78:3306/test?useSSL=false
      username: chaxun
      password: chaxun
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 100000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 600000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 1
    fin_dw:
      driverClassName: com.cloudera.impala.jdbc4.Driver
      url: jdbc:impala://192.168.61.97:21050/fin_dw;AuthMech=3
      username: cdh_dev
      password: 123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 100000
      minEvictableIdleTimeMillis: 600000
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false      
      validationQuery: SELECT 1





      